eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: @pom.artifactId@
  zipkin:
    base:
      url: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:3306/sns?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  redis:
    #数据库索引
    database: 2
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 300s

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.clim.friend.model.entity